// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdata_init.cpp"
#include "Vdata_init___024root__DepSet_h04cb635d__0.cpp"
#include "Vdata_init___024root__DepSet_h4ff71977__0.cpp"
#include "Vdata_init__ConstPool_0.cpp"
#include "Vdata_init___024root__Slow.cpp"
#include "Vdata_init___024root__DepSet_h4ff71977__0__Slow.cpp"
#include "Vdata_init___024unit__Slow.cpp"
#include "Vdata_init___024unit__DepSet_h533fb0e8__0__Slow.cpp"
#include "Vdata_init__Syms.cpp"
